

INSERT INTO user (username, role,  firstName, lastName, password,address, phone, zipcode, created, updated) VALUES ('admin', 0, 'admin', 'admin', '$2a$10$2f0EGxg500UFbQZ5VCNx4uhi8KkAY7lAKGAxORTnjztC4m5w0FEM6', 'test', '1234', '22222', NOW(), NOW());

INSERT INTO user (username, role,  firstName, lastName, password,address, phone, zipcode, created, updated) VALUES ('gs', 1, 'Shang', 'Gao', '$2a$10$2f0EGxg500UFbQZ5VCNx4uhi8KkAY7lAKGAxORTnjztC4m5w0FEM6', 'test', '1234', '22222', NOW(), NOW());


INSERT INTO category(name,description) VALUES('Computer','Computer boos are very effective for knowing and career! You can be an expert by following the rules and practising regularly.')
INSERT INTO category(name,description) VALUES('History','History books are very informative! You make a bridge between eras through history.')
INSERT INTO category(name,description) VALUES('Sports','Sports books are very interesting and informative! You can learn different rules and regulations about sports.')



INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Java Book','Java is a general-purpose computer programming language that is concurrent, class-based, object-oriented, and specifically designed to have as few implementation dependencies as possible.',40,1, "/images/9.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('C# Book','C#  is an object-oriented programming language from Microsoft that aims to combine the computing power of C++ with the programming ease of Visual Basic. C# is based on C++ and contains features similar to those of Java.',50,1, "/images/2.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Machine Learning','Machine learning is a field of computer science that gives computers the ability to learn without being explicitly programmed. Arthur Samuel, an American pioneer in the field of computer gaming and artificial intelligence, coined the term "Machine Learning" in 1959 while at IBM.',44,1, "/images/3.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Web Application Architecture','The server renders and returns HTML pages to the client, which the browser can display. The core of a Web application is its server-side logic. The application can contain several distinct layers. The typical example is a three-layered architecture comprised of presentation, business, and data layers.',70,1, "/images/4.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Spring MVC and Microservices','Spring Web MVC is the original web framework built on the Servlet API and included in the Spring Framework from the very beginning. The formal name "Spring Web MVC" comes from the name of its source module spring-webmvc but it is more commonly known as "Spring MVC".',30,1, "/images/6.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Embedded Networking','Embedded Serial Device Servers. Moxas embedded networking embedded device server series includes embedded serial-to-ethernet device servers.',45,1, "/images/7.png")

INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Modern History','The term modern was coined in the 16th century to indicate present or recent times (ultimately derived from the Latin adverb modo, meaning "just now").[14] The European Renaissance (about 1420–1630), which marked the transition between the Late Middle Ages and Early Modern times.',50,2, "/images/1.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Mona Lisa','The title of the painting, which is known in English as Mona Lisa, comes from a description by Renaissance art historian Giorgio Vasari, who wrote "Leonardo undertook to paint, for Francesco del Giocondo, the portrait of Mona Lisa, his wife."[11][12] Mona in Italian is a polite form of address originating as "ma donna" – similar to "Ma’am", "Madam".',55,2, "/images/6.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Water Fight','A water fight is a type of mock combat using various water-dispensing devices to soak opponents. Everything from buckets to balloons to water guns and even cupped hands cradling water can be applied in a water fight. There are many different levels of game play used by those engaging in water fights, from quick, casual fights to long, objective-oriented-style water.',77,2, "/images/2.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('History of Cricket','Cricket is a bat-and-ball game played between two teams of eleven players each on a cricket field, at the centre of which is a rectangular 22-yard-long pitch with a target called the wicket (a set of three wooden stumps topped by two bails) at each end.',32,2, "/images/4.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('History of Football','Records trace the history of soccer back more than 2,000 years ago to ancient China. Greece, Rome, and parts of Central America also claim to have started the sport; but it was England that transitioned soccer, or what the British and many other people around the world call “football,” into the game we know today.',50,2, "/images/5.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('American Revolution','The American Revolution was a colonial revolt that took place between 1765 and 1783. The American Patriots in the Thirteen Colonies won independence from Great Britain, becoming the United States of America. They defeated the British in the American Revolutionary War in alliance with France and others',40,2, "/images/9.png")

INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Soccer Game','Association football, more commonly known as football or soccer,[a] is a team sport played between two teams of eleven players with a spherical ball. It is played by 250 million players in over 200 countries and dependencies, making it the worlds most popular sport',66,3, "/images/2.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Cricket Game','Cricket is a bat-and-ball game played between two teams of eleven players each on a cricket field, at the centre of which is a rectangular 22-yard-long pitch with a target called the wicket (a set of three wooden stumps topped by two bails) at each end.',22,3, "/images/7.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Puzzle Games','Play Puzzle Games on Miniclip. Our top Puzzle games are Bubble Trouble, Bloxorz, and Color Switch - and we have over 249 other Puzzle games to enjoy!',48,3, "/images/5.png")
INSERT INTO book(title,description,price,categoryId, imagePath) VALUES('Ludo Game','Pachisi originated in India by the 6th century.[2] The earliest evidence of this game in India is the depiction of boards on the caves of Ajanta.[2] This game was played by the Mughal emperors of India; a notable example is AKbar.',55,3, "/images/4.png")
